image: node:12.14.0
options:
  size: 2x
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - node -v
            - npm -v
            - npm i
            - npm run build:$BITBUCKET_BRANCH
            - cd dist
            - pipe: atlassian/aws-s3-deploy:0.3.5
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_PROD
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_PROD
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_PROD
                S3_BUCKET: $S3_BUCKET_PROD
                LOCAL_PATH: "$(pwd)"
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_PROD
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_PROD
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_PROD
                DISTRIBUTION_ID: $AWS_SINF_DIST_PROD
                PATHS: "/*"

    '{dev,qc,staging}':
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - node -v
            - npm -v
            - npm i
            - npm run build:$BITBUCKET_BRANCH
            - cd dist
            - pipe: atlassian/aws-s3-deploy:0.3.5
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET/$BITBUCKET_BRANCH
                LOCAL_PATH: "$(pwd)"
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $AWS_SINF_DIST_$BITBUCKET_BRANCH
                PATHS: "/*"
                